In [3]:
import numpy as np
 
# Visualization
import open3d as o3d
 

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
pc_np = np.load('./data/shapenet_04554684-fcc0bdba1a95be2546cde67a6a1ea328.npy')
print('Shape of the Point Cloud:', pc_np.shape)
# Create PointCloud class
pc = o3d.geometry.PointCloud()
pc.points = o3d.utility.Vector3dVector(pc_np)

Shape of the Point Cloud: (8192, 3)


In [3]:
# visualization
o3d.visualization.draw_geometries([pc])

In [70]:
# pc_txt = np.loadtxt('./data/modelnet40_airplane_0001.txt', delimiter=',')
pc_txt =  np.loadtxt('./data/test.txt', delimiter=',')

print('Shape of the point cloud:', pc_txt.shape)
points = pc_txt[:,:3]
colors = pc_txt[:,3:] 
print(points)
print(colors)




Shape of the point cloud: (476666, 6)
[[-5.79850817e+00 -7.10112454e-16  1.55370557e+00]
 [-5.94198275e+00 -1.99224744e-02  1.59215832e+00]
 [-6.01850891e+00 -4.03585657e-02  1.61269081e+00]
 ...
 [-1.36931467e+00  9.18193813e-03 -3.66914988e-01]
 [-1.36890852e+00  4.58939001e-03 -3.66800010e-01]
 [-1.36848688e+00 -3.31706531e-07 -3.66684943e-01]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 ...
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[-3.49832535e+00 -4.28421297e-16  9.37373459e-01]
 [-3.50275445e+00 -1.17441509e-02  9.38565552e-01]
 [-3.50719619e+00 -2.35183518e-02  9.39771533e-01]
 ...
 [-1.35987461e+00  9.11863800e-03 -3.64385486e-01]
 [-1.35976624e+00  4.55873972e-03 -3.64350319e-01]
 [-1.35964262e+00 -3.29562795e-07 -3.64315152e-01]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 ...
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [1]:
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(points)
pcd.colors = o3d.utility.Vector3dVector(colors*0.0)

vis = o3d.visualization.Visualizer()
vis.create_window()
vis.add_geometry(pcd)
vis.update_geometry(pcd)
vis.poll_events()
vis.update_renderer()

# visualization
o3d.visualization.draw_geometries([pcd])


NameError: name 'o3d' is not defined

In [ ]:
import open3d as o3d
import numpy as np
import time
import socket

# create visualizer and window.
vis = o3d.visualization.Visualizer()
vis.create_window(height=480, width=640)

# initialize pointcloud instance.
pcd = o3d.geometry.PointCloud()
# *optionally* add initial points
points = np.random.rand(10, 3)
pcd.points = o3d.utility.Vector3dVector(points)

# include it in the visualizer before non-blocking visualization.
vis.add_geometry(pcd)

# to add new points each dt secs.
dt = 1
# number of points that will be added
n_new = 10

previous_t = time.time()
filepath = "/home/admin2/ros-tcp-unity/src/unity_robotics_demo/scripts/data/test.txt"
 

# run non-blocking visualization. 
# To exit, press 'q' or click the 'x' of the window.
keep_running = True
while keep_running:    
    if time.time() - previous_t > dt:
        # Options (uncomment each to try them out):
        # 1) extend with ndarrays.
        loaded_array = np.loadtxt(filepath, delimiter=',') 

        points = loaded_array # np.random.rand(n_new, 3)
        pcd.points.extend(points)
        
        # 2) extend with Vector3dVector instances.
        # pcd.points.extend(
        #     o3d.utility.Vector3dVector(np.random.rand(n_new, 3)))        
        # 3) other iterables, e.g
        # pcd.points.extend(np.random.rand(n_new, 3).tolist())
        
        vis.update_geometry(pcd)
        previous_t = time.time()
        print(points[0])
        print(len( pcd.points))

    keep_running = vis.poll_events()
    vis.update_renderer()

vis.destroy_window() 

In [22]:
# producer_script.py
# ray or redis to pass variable btween script

ModuleNotFoundError: No module named 'ray'